build:
  version: "1.0"

spring:
  datasource:
    master:
      jdbc-url: jdbc:mysql://itemservice-master:3310/itemservice
      username: root
      password: wxwwxw123
      driver-class-name: com.mysql.cj.jdbc.Driver
    slave:
      jdbc-url: jdbc:mysql://itemservice-slave:3311/itemservice
      username: root
      password: wxwwxw123
      driver-class-name: com.mysql.cj.jdbc.Driver

keycloak:
  auth-server-url: "keycloak:http://keycloak:7080"
  realm: "XianweiECommerce"
  client-id: "xianwei-ecommerce"
  client-secret: "g5HFcWL6MHBFnrAe9FO0HhlMipOHzFNZ"
  master-id: "admin-cli"
  master-secret: ""
  admin-username: "admin"
  admin-password: "admin"

item:
  message: "This is XianweiECommerce's item  micro service"
  contactDetails:
    name: "Xianwei Wu - Developer"
    email: "xianwew@gamil.com"
  onCallSupport:
    xxxxxxxxxx
