build:
  version: "1.0"

spring:
  datasource:
    master:
      url: jdbc:mysql://localhost:3309/orderservice
      username: root
      password: wxwwxw123
      driver-class-name: com.mysql.cj.jdbc.Driver
    slave:
      url: jdbc:mysql://localhost:3310/orderservice
      username: root
      password: wxwwx123
      driver-class-name: com.mysql.cj.jdbc.Driver

keycloak:
  auth-server-url: "http://localhost:7080"
  realm: "XianweiECommerce"
  client-id: "xianwei-ecommerce"
  client-secret: "g5HFcWL6MHBFnrAe9FO0HhlMipOHzFNZ"
  master-id: "admin-cli"
  master-secret: ""
  admin-username: "admin"
  admin-password: "admin"

order:
  message: "This is XianweiECommerce's order micro service"
  contactDetails:
    name: "Xianwei Wu - Developer"
    email: "xianwew@gamil.com"
  onCallSupport:
    xxxxxxxxxx
