build:
  version: "1.0"

spring:
  datasource:
    master:
      jdbc-url: jdbc:mysql://localhost:3307/userservice
      username: root
      password: wxwwxw123
      driverClassName: com.mysql.cj.jdbc.Driver
    slave:
      jdbc-url: jdbc:mysql://localhost:3308/userservice
      username: root
      password: wxwwxw123
      driverClassName: com.mysql.cj.jdbc.Driver

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/

itemservice:
  url: http://localhost:8040/api/item

keycloak:
  auth-server-url: "http://localhost:7080"
  realm: "XianweiECommerce"
  client-id: "xianwei-ecommerce"
  client-secret: "g5HFcWL6MHBFnrAe9FO0HhlMipOHzFNZ"
  master-id: "admin-cli"
  master-secret: ""
  admin-username: "admin"
  admin-password: "admin"

user:
  message: "This is XianweiEComeerce's user micro service"
  contactDetails:
    name: "Xianwei Wu - Developer"
    email: "xianwew@gamil.com"
  onCallSupport:
    xxxxxxxxxx
