build:
  version: "1.0"

spring:
  datasource:
    master:
      jdbc-url: jdbc:mysql://userservice-master:3306/userservice
      username: root
      password: wxwwxw123
      driver-class-name: com.mysql.cj.jdbc.Driver
    slave:
      jdbc-url: jdbc:mysql://userservice-slave:3306/userservice
      username: root
      password: wxwwxw123
      driver-class-name: com.mysql.cj.jdbc.Driver

itemservice:
  url: http://item:8040/api/item
    
keycloak:
  auth-server-url: "http://keycloak:8080"
  realm: "XianweiECommerce"
  client-id: "xianwei-ecommerce"
  client-secret: "g5HFcWL6MHBFnrAe9FO0HhlMipOHzFNZ"
  master-id: "admin-cli"
  master-secret: ""
  admin-username: "admin"
  admin-password: "admin"

user:
  message: "This is XianweiEComeerce's user micro service"
  contactDetails:
    name: "Xianwei Wu - Developer"
    email: "xianwew@gamil.com"
  onCallSupport:
    xxxxxxxxxx
